### ISSUE TITLE
Right Click Menu

### ISSUE THREAD

**Issue by djarbz** [ceodoe/noshitempornium#6]
Hello, awesome script!

I just started using it, I like the right click to add a tag to the black/whitelist, however, I still need a way to open in a new tab.
Would it be possible to add this to the menu override?

**Comment by ceodoe** [comment]
Hey! Pressing the middle mouse button will open a link in a new tab. If you have no middle mouse button or are using a touchpad/trackpad, you can also hold down Ctrl (Cmd on Mac) while left-clicking the link to open a new tab. 

If you need the browser right-click menu, hold down shift while right clicking (only works in Firefox), and it will show the context menu regardless. Worst case scenario, you can disable Right-Click Management from Options > Settings > Filtering.

**Comment by djarbz** [comment]
Ok, great, thanks!
