### ISSUE TITLE
Tag blacklist not taking any effect

### ISSUE THREAD

**Issue by glodomorrapl** [ceodoe/noshitempornium#7]
Removing/hiding torrents with blacklisted tags simply doesn't work for me. I provided the tags in the "tag blacklist" section, cleared out all other filtering options, pressed "Save" then "Reload page and apply changes". Page refreshes, all torrents are still there, nothing's filtered out. Not sure what I'm doing wrong.

Firefox 103.0.1, Tampermonkey 4.17.6161.

**Comment by ceodoe** [comment]
Sorry for the delayed response, I don't manually visit the repo that often and I hadn't got an email notification for this issue. 

I'm gonna need some more information from you. Are you running any other extensions or userscripts that interact with Emp in any way? Are any errors appearing in the browser console (F12) after loading a page where the script runs? Does this behaviour happen on one or more specific pages, or all of them? Do you get any different console errors on the various different pages? Does the NSE config area always appear regardless of whether it filters the actual content? I know that's a lot of questions at once, but really, any information you can provide about your execution environment is valuable, as this is a hard one to pin down and I've had a couple of others report similar issues but never been able to get to the bottom of them.

I'm also running the FF and Tampermonkey combo and I don't experience this. Can you try creating a new profile (Navigate to about:profiles in FF and create a new one), then install TM and the script in the new profile, log in to Emp and see if you still experience the issue? I've had scripts in the past stop working for inexplicable reasons, but start working again once I disable and re-enable Tampermonkey.

**Comment by glodomorrapl** [comment]
also sorry for delayed response lol

the only other userscript i have is a theme, which i turned off for testing and it didn't seem to change anything. any extensions that could potentially interfere with the website (ublock origin, dark reader) are excluded from working with that website.

the only things i see in the developer console are "JQMIGRATE: Migrate is installed with logging active, version 1.4.1" and "jQuery running in compatibility mode". testing on the main torrent page. the NSE config area always appears.

i have created a new FF profile as instructed, only tampermonkey and your script, same thing. nothing is filtered out from my tag blacklist.

**Comment by ceodoe** [comment]
Unfortunately I have tried a number of times, but I can't reproduce this issue. Feel free to open a new issue if you can provide some information that will help reproduce this issue (for example if you can reliably make it happen on several machines, browsers, OSes, etc)
