### ISSUE TITLE
[BUG] Blacklist just hiding

### ISSUE THREAD

**Issue by djarbz** [ceodoe/noshitempornium#9]
I have noticed that Blacklisted items are just hidden and not removed from the results.
The tag shows up in the darker red color to indicate it is recognized as Blacklisted vs Hidden.
I have no other TamperMonkey or similar extensions installed.
There is not a Whitelist tag in the list to keep it active.

The console shows the following messages in Verbose mode:
```
JQMIGRATE: Migrate is installed with logging active, version 1.4.1
script_start.js?v=1694607435:392 jQuery running in compatibility mode
[Violation] 'DOMContentLoaded' handler took 171ms
content.js:1 [Violation] 'DOMContentLoaded' handler took 177ms
[Violation] Forced reflow while executing JavaScript took 56ms
```

I am using:
- Chrome 127.0.6533.119
- TamperMonkey 5.2.1
- NSE 2.7.12

**Comment by ceodoe** [comment]
This is intended behaviour. Items matching your blacklist contents are hidden behind the toggle on purpose. If you wish to remove results entirely, enable the Hard Pass and Black Hole options in Options > Settings > Filtering, and use the Hard Pass blacklist instead of the regular blacklist.

**Comment by djarbz** [comment]
I apologize, I was using the wrong terminology.
When I said Blacklisted, I meant Hard Pass.
That being said, it looks like I did forget to check the Black Hole option.

Thank you
